<?php
require_once('functions.php');
$page_content=include_template('index.php',
    [
        'categories'=>$categories,
        'lots'=>$lots,
    ]);
$layout_content=include_template('layout.php',
    [
        'page_title'=>'Главная',
        'is_auth'=>$is_auth,
        'user_name'=>$user_name,
        'page_content'=>$page_content,
        'user_avatar'=>$user_avatar,
        'categories'=>$categories
    ]);
print($layout_content);
?>